<!DOCTYPE html>
<html>
    <head>
        <title>Administration</title>
        <script type="text/javascript" src="<?php echo $this->jQueryMin; ?>"></script>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->css; ?>/style.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo $this->css; ?>/modal.css" />
    </head>
    <?php if ($this->response > 0): ?>
        <script>
            $(document).ready(function() {
                <?php
                if ($this->response == 1) {
                    $message = "Nutzer wurde erfolgreich bearbeitet";
                }
                if ($this->response == 2) {
                    $message = "Nutzer wurde erfolgreich angelegt";
                }
                if ($this->response == 3) {
                    $message = "Nutzer wurde erfolgreich gel&ouml;scht";
                }
				if ($this->response == 4) {
                    $message = "Lernfeld wurde erfolgreich bearbeitet";
                }
                if ($this->response == 5) {
                    $message = "Lernfeld wurde erfolgreich angelegt";
                }
                if ($this->response == 6) {
                    $message = "Lernfeld wurde erfolgreich gel&ouml;scht";
                }
                ?>
                var data = $('<div style="background-color:greenyellow;padding:10px;"><h3><?php echo $message; ?></h3></div>');
                var popup = $('<div id="popup" style="border:2px solid green;">');
                popup.append(data);
                $('body').append(popup);
                popup.css("position", "absolute");
                popup.css("top", ($(window).height() - popup.height()) / 2 + $(window).scrollTop() + "px");
                popup.css("left", ($(window).width() - popup.width()) / 2 + $(window).scrollLeft() + "px");
                popup.hide();
                popup.fadeIn(1000, 'linear');
                popup.fadeOut(1000, 'linear');
            });
        </script>
    <?php endif; ?>
	
	
	
	<body>
	
	<div class="page">	
		<!--  Page navigation -->
		<div id="header"> </div>
		
		<div id="pagenavigation">
			<div id="navi_top">
					<a href="index.html">didaktische Jahresplanung</a> 
					<a href="<?php echo $this->adminUrl; ?>">Administration</a>
						 
			<!-- dynamischer Content angemeldeter User -->	
					<div style="float:right"> 
						<span style="margin-right:10px">angemeldet als <?php echo $this->user; ?></span>	
			<!-- löschen der browsermetadaten -->
					<a href="<?php echo $this->adminUrl . "?cmd=logout"; ?>" style="border-left:1px solid white">Logout</a> 	
				</div>
				</div>
			
		</div>
		<div class="clear_both"></div>
	
		<div id="content"> 		
			<div id="siteMenu">
				<ul class="menueliste">
					<li class="buttonMenu" ><a href="<?php echo $this->adminUrl . "?cmd=confuser"; ?>">Benutzer</a></li>
					<li class="buttonMenu" ><a href="<?php echo $this->adminUrl . "?cmd=confsubject";?>">F&auml;cher</a></li>
					<li class="buttonMenu" ><a href="<?php echo $this->adminUrl . "?cmd=confeducation"; ?>">Bildungsgang</a></li>
					<li class="buttonMenu"> <a href="<?php echo $this->adminUrl . "?cmd=conflfield"; ?>">Lernfelder </a></li>
				</ul>
			 </div>
			 
			<!-- dynamisches Laden der Teilinformationen -->
			<div class="administration">
		
				<?php echo $this->content; ?>
			 </div>

	</div> <!--  Content -->
	<div id="footer">
	
	</div> 
</div><!-- page -->
    </body>
</html>
