<h1>Bildungsgang</h1>
<a href="<?php echo $this->adminUrl."?cmd=confeducation&task=add"; ?>">Bildungsgang hinzuf&uuml;gen</a>
	<table class="admin_table">
		<tbody><tr>
            <th>K&uuml;rzel</th>
			<th>Bezeichnung</th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
		</tr>
        <?php foreach($this->educationList as $education):?>
		<tr>
			<td><?php echo $education["Name"];?></td>
			<td><?php echo $education["Beschreibung"];?></td>
			<td><a href="<?php echo $this->adminUrl."?cmd=confeducation&task=edit&id=".$education["Bildungsgang_Id"];?>">Bearbeiten</a></td>
			<td><a href="<?php echo $this->adminUrl."?cmd=confeducation&task=delete&id=".$education["Bildungsgang_Id"];?>" onclick="if(confirm('Wirklich l&ouml;schen ?')){return true;} return false;">L&ouml;schen</a></td>
		</tr>
        <?php endforeach;?>
	</tbody></table>
