<html>
<head>
	<link rel="stylesheet" type="text/css" href="css/modal.css" />
	<link rel="stylesheet" type="text/css" href="css/style.css" />
</head>
<body>

<div class="modalerDialogBildungsgangAnlegen">
	<div class="ueberschrift">
		Einen Bildungsgang anlegen
	</div>


<form method="post">
 	<div class="zeile" id="zeile1"> 
 		<div class="floatLeft">Name:<br/> <input name="name" style="width:330px" type="Text"/><br></div>
 	</div> <!--  Ende Zeile 1 -->	
	<div style="clear:both"> </div>
 	
 	<div class="zeile" id="zeile1"> 
 		<div class="floatLeft">Beschreibung:<br/> <input name="beschreibung" style="width:380px;height:250px" type="Text"/></div>
 	</div>
<div style="float:right;margin-right:20px;margin-top:20px;">
	<input class="inputbutton" type="submit" value="Speichern">
	<input class="inputbutton" type="button" value="abbrechen">
</div>
	<div style="clear:both"> </div>
</form>
 
</div> <!--  Ende Modaler Dialog -->

</body> 
</html>

