<h1>Bildungsg&auml;nge</h1>
<a class="inputbutton" href="<?php echo $this->adminUrl."?cmd=confrole&task=add"; ?>">Bildungsgang hinzuf&uuml;gen</a>
	<table class="admin_table">
		<tbody><tr>
            <th>Name</th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
		</tr>
        <?php foreach($this->roleList as $role):?>
		<tr>
			<td><?php echo $role["Name"];?></td>
			<td><a href="<?php echo $this->adminUrl."?cmd=confrole&task=edit&id=".$role["Typ_Id"];?>">Bearbeiten</a></td>
			<td><a href="<?php echo $this->adminUrl."?cmd=confrole&task=delete&id=".$role["Typ_Id"];?>" onclick="if(confirm('Wirklich l&ouml;schen ?')){return true;} return false;">L&ouml;schen</a></td>
		</tr>
        <?php endforeach;?>
	</tbody></table>
